version: '3.8'

services:
  my-vite:
    build:
      context: .
    container_name: my-vite
    image: my-vite
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
